import type { ReactNode } from "react";
import { createServerFn } from "@tanstack/react-start";
import { HeadContent, Scripts, createRootRoute } from "@tanstack/react-router";
import { ToastContainer } from "react-toastify";
import { ClerkProvider } from "@clerk/tanstack-react-start";
import { auth } from "@clerk/tanstack-react-start/server";
import appCss from "@/styles/app.css?url";

import { ThemeProvider } from "@/components/theme-provider";

const fetchClerkAuth = createServerFn({ method: "GET" }).handler(async () => {
  const { userId } = await auth();
  return {
    userId,
  };
});

export const Route = createRootRoute({
  beforeLoad: async () => {
    const { userId } = await fetchClerkAuth();

    return {
      userId,
    };
  },
  head: () => ({
    meta: [
      {
        charSet: "utf-8",
      },
      {
        name: "viewport",
        content: "width=device-width, initial-scale=1",
      },
      {
        title: "portfolio",
      },
      {
        name: "description",
        content: "TanStack Start + Prisma starter generated by create-prisma.",
      },
    ],
    links: [
      {
        rel: "stylesheet",
        href: appCss,
      },
    ],
  }),
  shellComponent: RootDocument,
  notFoundComponent: () => {
    return <p>Not Found Custom page</p>;
  },
});

function RootDocument({ children }: { children: ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <HeadContent />
      </head>
      <body>
        <ThemeProvider defaultTheme="system" storageKey="theme">
          <ClerkProvider>{children}</ClerkProvider>
          <ToastContainer />
        </ThemeProvider>
        <Scripts />
      </body>
    </html>
  );
}
