/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardTestimonialsRouteImport } from './routes/dashboard/testimonials'
import { Route as DashboardProjectsRouteImport } from './routes/dashboard/projects'
import { Route as DashboardExperienceRouteImport } from './routes/dashboard/experience'
import { Route as DashboardEducationRouteImport } from './routes/dashboard/education'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTestimonialsRoute = DashboardTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsRoute = DashboardProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardExperienceRoute = DashboardExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEducationRoute = DashboardEducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/education': typeof DashboardEducationRoute
  '/dashboard/experience': typeof DashboardExperienceRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/testimonials': typeof DashboardTestimonialsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/education': typeof DashboardEducationRoute
  '/dashboard/experience': typeof DashboardExperienceRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/testimonials': typeof DashboardTestimonialsRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/education': typeof DashboardEducationRoute
  '/dashboard/experience': typeof DashboardExperienceRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/testimonials': typeof DashboardTestimonialsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/education'
    | '/dashboard/experience'
    | '/dashboard/projects'
    | '/dashboard/testimonials'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/education'
    | '/dashboard/experience'
    | '/dashboard/projects'
    | '/dashboard/testimonials'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/education'
    | '/dashboard/experience'
    | '/dashboard/projects'
    | '/dashboard/testimonials'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/testimonials': {
      id: '/dashboard/testimonials'
      path: '/testimonials'
      fullPath: '/dashboard/testimonials'
      preLoaderRoute: typeof DashboardTestimonialsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/projects': {
      id: '/dashboard/projects'
      path: '/projects'
      fullPath: '/dashboard/projects'
      preLoaderRoute: typeof DashboardProjectsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/experience': {
      id: '/dashboard/experience'
      path: '/experience'
      fullPath: '/dashboard/experience'
      preLoaderRoute: typeof DashboardExperienceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/education': {
      id: '/dashboard/education'
      path: '/education'
      fullPath: '/dashboard/education'
      preLoaderRoute: typeof DashboardEducationRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardEducationRoute: typeof DashboardEducationRoute
  DashboardExperienceRoute: typeof DashboardExperienceRoute
  DashboardProjectsRoute: typeof DashboardProjectsRoute
  DashboardTestimonialsRoute: typeof DashboardTestimonialsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardEducationRoute: DashboardEducationRoute,
  DashboardExperienceRoute: DashboardExperienceRoute,
  DashboardProjectsRoute: DashboardProjectsRoute,
  DashboardTestimonialsRoute: DashboardTestimonialsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
